source "http://rubygems.org" 
gem 'fluentd', '0.12.39'

gem 'fluent-plugin-out-http', '0.2.0'
gem 'fluent-plugin-elasticsearch', '1.9.5'
gem 'fluent-plugin-rewrite-tag-filter', '1.5.6'
gem 'fluent-plugin-secure-forward', '0.4.5'
